spring:
  application:
    name: june25-library-backend
  datasource:
    url: jdbc:h2:./libraryDB
    username: sa
    password: sa123

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 9092
